before_script:
- sed -i "s#universe#universe multiverse#" /etc/apt/sources.list
- apt-get update
- apt-get install -qq --no-install-recommends ca-certificates

stages:
- build
- test

build-webrtc:
  stage: build
  script:
  - ./build.sh $REVISION
  cache:
    paths:
    - out
  artifacts:
    expire_in: 6 months
    paths:
    - out/*.zip

test-webrtc:
  stage: test
  before_script:
  - apt-get update
  - apt-get install -qq --no-install-recommends unzip pkg-config g++ libssl-dev
    libnss3-dev libx11-dev libexpat1-dev libasound2
  script:
  - cd out; unzip *.zip; cd -
  - test/run_tests.sh $(ls -d -1 out/webrtc*/)
  dependencies:
  - build-webrtc
